name: Auto-update Changelog

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'CHANGELOG.md'
      - '.github/workflows/**'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: next-version
        run: |
          # Get latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LATEST_VERSION=${LATEST_TAG#v}
          
          # Increment patch version
          IFS='.' read -ra VERSION_PARTS <<< "$LATEST_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          NEXT_PATCH=$((PATCH + 1))
          
          NEXT_VERSION="${MAJOR}.${MINOR}.${NEXT_PATCH}"
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "Next version will be: $NEXT_VERSION"

      - name: Update unreleased section
        uses: ./
        with:
          version: "Unreleased"
          changelog-path: 'CHANGELOG.md'
          format: '- {{subject}} by @{{author}}'
          exclude-patterns: 'chore:,ci:,docs:,Update release notes,Auto-update changelog'
          auto-commit: 'true'
          commit-message: 'docs: auto-update changelog [skip ci]'
