name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.2.3)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate version format
        run: |
          if ! [[ "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in format X.Y.Z"
            exit 1
          fi

      - name: Check if tag exists
        run: |
          if git rev-parse "v${{ inputs.version }}" >/dev/null 2>&1; then
            echo "Error: Tag v${{ inputs.version }} already exists"
            exit 1
          fi

      - name: Generate Release Notes
        id: release-notes
        uses: ./
        with:
          version: ${{ inputs.version }}
          changelog-path: 'CHANGELOG.md'
          format: '- {{subject}} by @{{author}}'
          exclude-patterns: 'chore:,ci:,docs:,Update release notes,Merge pull request'
          auto-commit: 'false'

      - name: Update version in action.yml
        run: |
          # Update any version references in documentation
          sed -i "s/multi-release-notes@v[0-9]\+\.[0-9]\+\.[0-9]\+/multi-release-notes@v${{ inputs.version }}/g" README.md
          sed -i "s/multi-release-notes@v[0-9]\+\.[0-9]\+\.[0-9]\+/multi-release-notes@v${{ inputs.version }}/g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "chore: release v${{ inputs.version }}"

      - name: Create tag and push
        run: |
          git tag -a "v${{ inputs.version }}" -m "Release v${{ inputs.version }}"
          git push origin main --follow-tags

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          body: ${{ steps.release-notes.outputs.release-notes }}
          draft: false
          prerelease: ${{ inputs.prerelease }}
          generate_release_notes: false

      - name: Update major version tag
        run: |
          MAJOR_VERSION=$(echo "${{ inputs.version }}" | cut -d. -f1)
          git tag -fa "v${MAJOR_VERSION}" -m "Update major version tag"
          git push origin "v${MAJOR_VERSION}" --force
